import { MapNodeData, Message } from './types';

export const initialNodes: MapNodeData[] = [
  {
    id: '0',
    title: 'Team 3 CPSC 4140',
    parentId: null,
    summary: 'Semester project chat organized into semantic topic clusters.',
    metadata: {},
    decisions: [],
    supportingMessageIds: [],
    childrenIds: ['1', '2', '3', '4', '5'],
    depth: 0,
  },
  {
    id: '1',
    title: 'Team Coordination',
    parentId: '0',
    summary: 'Team logistics, communication choices, and coordination setup.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['1.1', '1.2'],
    depth: 1,
  },
  {
    id: '1.1',
    title: 'Meeting Setup',
    parentId: '1',
    summary: 'Choosing and confirming a recurring meeting schedule.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: '1.2',
    title: 'Communication and Task Tracking',
    parentId: '1',
    summary: 'Agreement on communication channels and task tracking tools.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: '2',
    title: 'Problem Understanding',
    parentId: '0',
    summary: 'Framing the problem and analyzing user needs through evidence.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['2.1', '2.2'],
    depth: 1,
  },
  {
    id: '2.1',
    title: 'Problem Exploration',
    parentId: '2',
    summary: 'Initial exploration of candidate problem areas and rationale.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: '2.2',
    title: 'Problem Analysis',
    parentId: '2',
    summary: 'Focused analysis of stakeholders, tools, tasks, and research methods.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['2.2.1', '2.2.2', '2.2.3', '2.2.4'],
    depth: 2,
  },
  {
    id: '2.2.1',
    title: 'Stakeholders',
    parentId: '2.2',
    summary: 'Who is impacted and who needs visibility into group progress.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: '2.2.2',
    title: 'Existing Tools',
    parentId: '2.2',
    summary: 'Current collaboration tools and limitations of timeline-only chat.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: '2.2.3',
    title: 'User Tasks',
    parentId: '2.2',
    summary: 'Critical tasks users need to complete in project discussions.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: '2.2.4',
    title: 'Research Methods',
    parentId: '2.2',
    summary: 'Interview and background research approach for validation.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: '3',
    title: 'Design Process',
    parentId: '0',
    summary: 'Generating concepts, comparing tradeoffs, and selecting direction.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['3.1', '3.2'],
    depth: 1,
  },
  {
    id: '3.1',
    title: 'Design Concepts',
    parentId: '3',
    summary: 'Distinct concept candidates for solving conversation structure problems.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['3.1.1', '3.1.2', '3.1.3'],
    depth: 2,
  },
  {
    id: '3.1.1',
    title: 'Chat Mapping',
    parentId: '3.1',
    summary: 'Concept focused on mapping chat into explicit topic branches.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: '3.1.2',
    title: 'Mobile Summary',
    parentId: '3.1',
    summary: 'Mobile concept focused on concise updates and what changed.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: '3.1.3',
    title: 'Project Dashboard',
    parentId: '3.1',
    summary: 'Dashboard concept for project status and responsibility tracking.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: '3.2',
    title: 'Design Comparison',
    parentId: '3',
    summary: 'Concept tradeoffs and final selection discussion.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['3.2.1', '3.2.2'],
    depth: 2,
  },
  {
    id: '3.2.1',
    title: 'Strengths and Weaknesses',
    parentId: '3.2',
    summary: 'Comparative discussion of benefits and limitations across concepts.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: '3.2.2',
    title: 'Chosen Direction',
    parentId: '3.2',
    summary: 'Final direction selected for the prototype.',
    metadata: {},
    decisions: ['Proceed with chat mapping as the prototype direction.'],
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: '4',
    title: 'Prototype & Evaluation',
    parentId: '0',
    summary: 'Prototype scope, evaluation strategy, and implementation constraints.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['4.1', '4.2', '4.3'],
    depth: 1,
  },
  {
    id: '4.1',
    title: 'Prototype Planning',
    parentId: '4',
    summary: 'Scoping core interactive features and documentation needs.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['4.1.1', '4.1.2'],
    depth: 2,
  },
  {
    id: '4.1.1',
    title: 'Core Features',
    parentId: '4.1',
    summary: 'Essential features required for the interactive prototype.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: '4.1.2',
    title: 'Documentation',
    parentId: '4.1',
    summary: 'Walkthrough narrative and report screenshots.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: '4.2',
    title: 'Evaluation',
    parentId: '4',
    summary: 'Quantitative and qualitative methods to assess usability.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['4.2.1', '4.2.2'],
    depth: 2,
  },
  {
    id: '4.2.1',
    title: 'Quantitative Benchmarks',
    parentId: '4.2',
    summary: 'Time, click-count, and task completion benchmarks.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: '4.2.2',
    title: 'Qualitative Methods',
    parentId: '4.2',
    summary: 'Think-aloud and follow-up interview feedback.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: '4.3',
    title: 'Implementation Challenges',
    parentId: '4',
    summary: 'Challenges in splitting topics and justifying leaf-level structure.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: '5',
    title: 'General',
    parentId: '0',
    summary: 'General project chat that does not fit a specific topic branch yet.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 1,
  },
];

export const initialMessages: Message[] = [
  { id: 'msg-1', sender: 'Jack', text: 'We need to pick a consistent meeting time before Milestone 0 is due.', timestamp: 'Sep 3, 5:01 PM', nodeIds: ['1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-2', sender: 'Boyd', text: 'Tuesdays or Wednesdays would probably work best for me.', timestamp: 'Sep 3, 5:02 PM', nodeIds: ['1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-3', sender: 'Emmanuel', text: 'Tuesday evenings are good for me.', timestamp: 'Sep 3, 5:03 PM', nodeIds: ['1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-4', sender: 'Graham', text: 'Same here, Tuesday after 5 works.', timestamp: 'Sep 3, 5:04 PM', nodeIds: ['1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-5', sender: 'Jack', text: 'Let\'s just do Tuesday at 6 then.', timestamp: 'Sep 3, 5:05 PM', nodeIds: ['1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-6', sender: 'Boyd', text: 'Works for me.', timestamp: 'Sep 3, 5:06 PM', nodeIds: ['1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-7', sender: 'Emmanuel', text: 'Same.', timestamp: 'Sep 3, 5:07 PM', nodeIds: ['1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-8', sender: 'Graham', text: 'Good with me too.', timestamp: 'Sep 3, 5:08 PM', nodeIds: ['1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-9', sender: 'Jack', text: 'Alright Tuesday at 6 is our weekly meeting time.', timestamp: 'Sep 3, 5:09 PM', nodeIds: ['1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-10', sender: 'Boyd', text: 'Let\'s use Teams for updates and Planner for task tracking so everything stays organized.', timestamp: 'Sep 3, 5:10 PM', nodeIds: ['1.2'], autoMapped: true, assignedManually: false },

  { id: 'msg-11', sender: 'Jack', text: 'For Milestone 1 we need to come up with three possible problem areas first.', timestamp: 'Sep 10, 6:01 PM', nodeIds: ['2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-12', sender: 'Boyd', text: 'One could be helping student teams stay on top of deadlines.', timestamp: 'Sep 10, 6:02 PM', nodeIds: ['2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-13', sender: 'Emmanuel', text: 'Another could be keeping group members accountable.', timestamp: 'Sep 10, 6:03 PM', nodeIds: ['2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-14', sender: 'Graham', text: 'I think the most interesting one is how project chats get messy and hard to navigate.', timestamp: 'Sep 10, 6:04 PM', nodeIds: ['2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-15', sender: 'Jack', text: 'Yeah especially when important decisions get buried in long conversations.', timestamp: 'Sep 10, 6:05 PM', nodeIds: ['2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-16', sender: 'Boyd', text: 'If we go with that, the main stakeholders are definitely students in team-based classes.', timestamp: 'Sep 10, 6:06 PM', nodeIds: ['2.2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-17', sender: 'Emmanuel', text: 'Maybe instructors too, since they sometimes need to understand group progress.', timestamp: 'Sep 10, 6:07 PM', nodeIds: ['2.2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-18', sender: 'Graham', text: 'We should also look at what people already use now.', timestamp: 'Sep 10, 6:08 PM', nodeIds: ['2.2.2'], autoMapped: true, assignedManually: false },
  { id: 'msg-19', sender: 'Jack', text: 'Mostly Teams, Discord, texts, and maybe shared docs.', timestamp: 'Sep 10, 6:09 PM', nodeIds: ['2.2.2'], autoMapped: true, assignedManually: false },
  { id: 'msg-20', sender: 'Boyd', text: 'The problem is those tools keep everything in one timeline instead of organizing the discussion.', timestamp: 'Sep 10, 6:10 PM', nodeIds: ['2.2.2'], autoMapped: true, assignedManually: false },
  { id: 'msg-21', sender: 'Emmanuel', text: 'The main tasks are probably finding past decisions, catching up, and seeing who is responsible for what.', timestamp: 'Sep 10, 6:11 PM', nodeIds: ['2.2.3'], autoMapped: true, assignedManually: false },
  { id: 'msg-22', sender: 'Graham', text: 'For methods we could do interviews and some background research.', timestamp: 'Sep 10, 6:12 PM', nodeIds: ['2.2.4'], autoMapped: true, assignedManually: false },
  { id: 'msg-23', sender: 'Jack', text: 'Yeah let\'s each talk to at least one or two people with group project experience.', timestamp: 'Sep 10, 6:13 PM', nodeIds: ['2.2.4'], autoMapped: true, assignedManually: false },
  { id: 'msg-24', sender: 'Boyd', text: 'That should give us enough to justify the problem area.', timestamp: 'Sep 10, 6:14 PM', nodeIds: ['2.2.4'], autoMapped: true, assignedManually: false },

  { id: 'msg-25', sender: 'Jack', text: 'For Milestone 2 we need three really different designs, not just three similar screens.', timestamp: 'Sep 17, 6:01 PM', nodeIds: ['3.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-26', sender: 'Boyd', text: 'One option is a chat interface that maps messages into topics visually.', timestamp: 'Sep 17, 6:02 PM', nodeIds: ['3.1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-27', sender: 'Emmanuel', text: 'Another could be a mobile summary app that just shows what changed.', timestamp: 'Sep 17, 6:03 PM', nodeIds: ['3.1.2'], autoMapped: true, assignedManually: false },
  { id: 'msg-28', sender: 'Graham', text: 'A third option could be a project dashboard that tracks status and responsibilities.', timestamp: 'Sep 17, 6:04 PM', nodeIds: ['3.1.3'], autoMapped: true, assignedManually: false },
  { id: 'msg-29', sender: 'Jack', text: 'The mapping interface feels the most unique to me.', timestamp: 'Sep 17, 6:05 PM', nodeIds: ['3.1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-30', sender: 'Boyd', text: 'Same, because it actually addresses the conversation structure itself.', timestamp: 'Sep 17, 6:06 PM', nodeIds: ['3.1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-31', sender: 'Emmanuel', text: 'The mobile summary one is simpler, but it probably would not help with deep conversations as much.', timestamp: 'Sep 17, 6:07 PM', nodeIds: ['3.1.2'], autoMapped: true, assignedManually: false },
  { id: 'msg-32', sender: 'Graham', text: 'And the dashboard is useful, but it doesn\'t really solve the buried-chat problem.', timestamp: 'Sep 17, 6:08 PM', nodeIds: ['3.1.3'], autoMapped: true, assignedManually: false },
  { id: 'msg-33', sender: 'Jack', text: 'We should still document strengths and weaknesses for each one.', timestamp: 'Sep 17, 6:09 PM', nodeIds: ['3.2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-34', sender: 'Boyd', text: 'The mapping idea is strongest for exploring branches of discussion and decision history.', timestamp: 'Sep 17, 6:10 PM', nodeIds: ['3.2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-35', sender: 'Emmanuel', text: 'The downside is that it could take users longer to learn at first.', timestamp: 'Sep 17, 6:11 PM', nodeIds: ['3.2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-36', sender: 'Graham', text: 'Even with that, I still think that is the best direction for the prototype.', timestamp: 'Sep 17, 6:12 PM', nodeIds: ['3.2.2'], autoMapped: true, assignedManually: false },

  { id: 'msg-37', sender: 'Jack', text: 'For Milestone 3 we only need an interactive front end, so the backend can be simulated.', timestamp: 'Oct 1, 7:01 PM', nodeIds: ['4.1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-38', sender: 'Boyd', text: 'Then we should focus on core features instead of trying to build everything.', timestamp: 'Oct 1, 7:02 PM', nodeIds: ['4.1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-39', sender: 'Emmanuel', text: 'Definitely Chat View, Map View, and a way to inspect messages inside topics.', timestamp: 'Oct 1, 7:03 PM', nodeIds: ['4.1.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-40', sender: 'Graham', text: 'We also need a clear walkthrough with screenshots for the report.', timestamp: 'Oct 1, 7:04 PM', nodeIds: ['4.1.2'], autoMapped: true, assignedManually: false },
  { id: 'msg-41', sender: 'Jack', text: 'For evaluation, we should define measurable success for important tasks.', timestamp: 'Oct 1, 7:05 PM', nodeIds: ['4.2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-42', sender: 'Boyd', text: 'One benchmark could be how fast a user can find a past decision.', timestamp: 'Oct 1, 7:06 PM', nodeIds: ['4.2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-43', sender: 'Emmanuel', text: 'Another could be the number of clicks it takes to get to messages in a topic.', timestamp: 'Oct 1, 7:07 PM', nodeIds: ['4.2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-44', sender: 'Graham', text: 'We could also track whether they complete the task at all without getting lost.', timestamp: 'Oct 1, 7:08 PM', nodeIds: ['4.2.1'], autoMapped: true, assignedManually: false },
  { id: 'msg-45', sender: 'Jack', text: 'For qualitative feedback, think-aloud seems like the best option.', timestamp: 'Oct 1, 7:09 PM', nodeIds: ['4.2.2'], autoMapped: true, assignedManually: false },
  { id: 'msg-46', sender: 'Boyd', text: 'Yeah and maybe a few short follow-up interview questions after.', timestamp: 'Oct 1, 7:10 PM', nodeIds: ['4.2.2'], autoMapped: true, assignedManually: false },
  { id: 'msg-47', sender: 'Emmanuel', text: 'One design challenge is deciding when a broad topic should split into a more specific node.', timestamp: 'Oct 1, 7:11 PM', nodeIds: ['4.3'], autoMapped: true, assignedManually: false },
  { id: 'msg-48', sender: 'Graham', text: 'Another is when a topic has enough related messages to justify its own leaf.', timestamp: 'Oct 1, 7:12 PM', nodeIds: ['4.3'], autoMapped: true, assignedManually: false },
  { id: 'msg-49', sender: 'Jack', text: 'We should definitely mention those implementation challenges in the report.', timestamp: 'Oct 1, 7:13 PM', nodeIds: ['4.3'], autoMapped: true, assignedManually: false },
  { id: 'msg-50', sender: 'Boyd', text: 'Agreed, and this milestone-based example should make the prototype easier to explain during the demo.', timestamp: 'Oct 1, 7:14 PM', nodeIds: ['4.3'], autoMapped: true, assignedManually: false },
  { id: 'msg-51', sender: 'Graham', text: 'Quick check-in: are we still on track overall for this week?', timestamp: 'Oct 1, 7:18 PM', nodeIds: ['5'], autoMapped: true, assignedManually: false },
  { id: 'msg-52', sender: 'Emmanuel', text: 'I think the flow is making more sense now compared to last week.', timestamp: 'Oct 1, 7:19 PM', nodeIds: ['5'], autoMapped: true, assignedManually: false },
  { id: 'msg-53', sender: 'Jack', text: 'Nice progress today everyone, this should be easier to demo now.', timestamp: 'Oct 1, 7:20 PM', nodeIds: ['5'], autoMapped: true, assignedManually: false },
];

export const initialExpandedNodeIds = ['0'];
