import { MapNodeData, Message } from './types';

// Wizard-of-Oz prototype seed data lives here.
export const initialNodes: MapNodeData[] = [
  {
    id: 'root-dev-team',
    title: 'Dev Team',
    parentId: null,
    summary: 'Root conversation map for the team chat session.',
    metadata: {},
    decisions: [],
    supportingMessageIds: [],
    childrenIds: ['topic-auth', 'topic-api', 'topic-ui', 'topic-deploy', 'topic-meeting', 'topic-general'],
    depth: 0,
  },
  {
    id: 'topic-auth',
    title: 'Authentication Questions',
    parentId: 'root-dev-team',
    summary: 'Collection of all authentication-related issues and questions discussed by the team.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['auth-401', 'auth-refresh', 'auth-logout'],
    depth: 1,
  },
  {
    id: 'topic-api',
    title: 'API Clarifications',
    parentId: 'root-dev-team',
    summary: 'Questions around endpoint shape, request payloads, and expected responses.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['api-response-shape', 'api-validation'],
    depth: 1,
  },
  {
    id: 'topic-ui',
    title: 'UI & Frontend Adjustments',
    parentId: 'root-dev-team',
    summary: 'Frontend implementation notes, layout updates, and design tweaks.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['ui-layout', 'ui-button-states'],
    depth: 1,
  },
  {
    id: 'topic-deploy',
    title: 'Deployment & Environment Issues',
    parentId: 'root-dev-team',
    summary: 'Environment variables, Docker setup, and deployment blockers.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['deploy-docker-env', 'deploy-postgres'],
    depth: 1,
  },
  {
    id: 'topic-meeting',
    title: 'Meeting & Coordination',
    parentId: 'root-dev-team',
    summary: 'Team sync scheduling and coordination updates.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['meeting-sprint-planning'],
    depth: 1,
  },
  {
    id: 'topic-general',
    title: 'General Conversation',
    parentId: 'root-dev-team',
    summary: 'General chat messages that do not fit a specific technical branch.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 1,
  },
  {
    id: 'auth-401',
    title: '401 Errors from Frontend',
    parentId: 'topic-auth',
    summary: 'Users experiencing unauthorized errors when making API requests after being logged in for some time.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['auth-401-missing-header', 'auth-401-expiration'],
    depth: 2,
  },
  {
    id: 'auth-refresh',
    title: 'Refresh Token Not Triggering',
    parentId: 'topic-auth',
    summary: 'Refresh logic did not trigger before token expiration in some user sessions.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'auth-logout',
    title: 'Logout Behavior Inconsistency',
    parentId: 'topic-auth',
    summary: 'Logout flows behaved differently across tabs and persisted stale state.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'auth-401-missing-header',
    title: 'Token Missing in Headers',
    parentId: 'auth-401',
    summary: 'API requests in one frontend flow were missing Authorization headers.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: 'auth-401-expiration',
    title: 'Access Token Expiration Timing',
    parentId: 'auth-401',
    summary: 'Team identified 401 errors were caused by access tokens expiring after 15 minutes without silent refresh.',
    metadata: {},
    decisions: ['Increase access token lifetime to 30 minutes', 'Implement automatic refresh before expiry'],
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: 'api-response-shape',
    title: 'Endpoint Response Shape',
    parentId: 'topic-api',
    summary: 'Clarifying fields and nested data returned by backend endpoints.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'api-validation',
    title: 'Request Validation & Error Codes',
    parentId: 'topic-api',
    summary: 'Handling payload validation and standardized API error responses.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'ui-layout',
    title: 'Layout Spacing vs Figma',
    parentId: 'topic-ui',
    summary: 'Differences in spacing and alignment compared to design specs.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'ui-button-states',
    title: 'Button States & Loading',
    parentId: 'topic-ui',
    summary: 'Improving disabled, loading, and hover states for clearer feedback.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'deploy-docker-env',
    title: 'Docker Environment Variables',
    parentId: 'topic-deploy',
    summary: 'Environment variable handling across local and staging Docker setups.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'deploy-postgres',
    title: 'Render Postgres Connectivity',
    parentId: 'topic-deploy',
    summary: 'Intermittent connection and SSL configuration issues with hosted Postgres.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'meeting-sprint-planning',
    title: 'Sprint Planning Schedule',
    parentId: 'topic-meeting',
    summary: 'Scheduling sprint planning, demos, and team availability.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
];

export const initialMessages: Message[] = [
  { id: 'msg-1', sender: 'Jack', text: 'Morning all. Login looks stable but I still saw one random 401 in staging.', timestamp: 'Mar 1, 9:14 AM', nodeIds: ['auth-401'], autoMapped: true, assignedManually: false },
  { id: 'msg-2', sender: 'Priya', text: 'Can you share the request headers from that failing call?', timestamp: 'Mar 1, 9:18 AM', nodeIds: ['auth-401-missing-header'], autoMapped: true, assignedManually: false },
  { id: 'msg-3', sender: 'Alex', text: 'I am checking interceptor logs now, maybe token missing in headers after refresh.', timestamp: 'Mar 1, 9:22 AM', nodeIds: ['auth-401-missing-header'], autoMapped: true, assignedManually: false },
  { id: 'msg-4', sender: 'Nina', text: 'Separate thread: API endpoint for project status now returns nested owner object.', timestamp: 'Mar 1, 9:29 AM', nodeIds: ['api-response-shape'], autoMapped: true, assignedManually: false },
  { id: 'msg-5', sender: 'Marco', text: 'Frontend card expects ownerName string. I will update the UI mapping.', timestamp: 'Mar 1, 9:33 AM', nodeIds: ['api-response-shape'], autoMapped: true, assignedManually: false },
  { id: 'msg-6', sender: 'Elena', text: 'Meeting note: can we keep daily sync at 10:30 for this sprint?', timestamp: 'Mar 1, 9:41 AM', nodeIds: ['meeting-sprint-planning'], autoMapped: true, assignedManually: false },
  { id: 'msg-7', sender: 'Derek', text: 'Works for me. I am blocked until docker env vars are fixed anyway.', timestamp: 'Mar 1, 9:43 AM', nodeIds: ['deploy-docker-env'], autoMapped: true, assignedManually: false },
  { id: 'msg-8', sender: 'Jack', text: 'I found it: auth header is empty when tab wakes from sleep.', timestamp: 'Mar 1, 10:02 AM', nodeIds: ['auth-401-missing-header'], autoMapped: true, assignedManually: false },
  { id: 'msg-9', sender: 'Priya', text: 'Can we add a guard so request is paused until token is restored?', timestamp: 'Mar 1, 10:08 AM', nodeIds: ['auth-401-missing-header'], autoMapped: true, assignedManually: false },
  { id: 'msg-10', sender: 'Alex', text: 'Also seeing refresh token not triggering before the 15 minute expiration.', timestamp: 'Mar 1, 10:14 AM', nodeIds: ['auth-refresh'], autoMapped: true, assignedManually: false },
  { id: 'msg-11', sender: 'Nina', text: 'API validation question: what status code for missing required field?', timestamp: 'Mar 1, 10:20 AM', nodeIds: ['api-validation'], autoMapped: true, assignedManually: false },
  { id: 'msg-12', sender: 'Marco', text: 'UI detail: loading button text shifts by 4px on submit.', timestamp: 'Mar 1, 10:26 AM', nodeIds: ['ui-button-states'], autoMapped: true, assignedManually: false },
  { id: 'msg-13', sender: 'Elena', text: 'I will send sprint agenda by end of day.', timestamp: 'Mar 1, 10:37 AM', nodeIds: ['meeting-sprint-planning'], autoMapped: true, assignedManually: false },
  { id: 'msg-14', sender: 'Derek', text: 'Docker compose file is missing AUTH_SECRET in staging env.', timestamp: 'Mar 1, 11:02 AM', nodeIds: ['deploy-docker-env'], autoMapped: true, assignedManually: false },
  { id: 'msg-15', sender: 'Jack', text: 'Frontend is getting 401 errors again after login. Happens after ~15 min inactivity.', timestamp: 'Mar 2, 2:07 PM', nodeIds: ['auth-401-expiration'], autoMapped: true, assignedManually: false },
  { id: 'msg-16', sender: 'Priya', text: 'Yeah the access token expiry window is too short without silent refresh.', timestamp: 'Mar 2, 2:12 PM', nodeIds: ['auth-401-expiration'], autoMapped: true, assignedManually: false },
  { id: 'msg-17', sender: 'Alex', text: 'I can increase access token lifetime to 30 minutes and add pre-expiry refresh.', timestamp: 'Mar 2, 2:18 PM', nodeIds: ['auth-401-expiration'], autoMapped: true, assignedManually: false },
  { id: 'msg-18', sender: 'Nina', text: 'API docs now list 422 for validation errors. Returning field-level details too.', timestamp: 'Mar 2, 2:34 PM', nodeIds: ['api-validation'], autoMapped: true, assignedManually: false },
  { id: 'msg-19', sender: 'Marco', text: 'Comparing with Figma, side panel padding should be 20 not 24.', timestamp: 'Mar 2, 2:47 PM', nodeIds: ['ui-layout'], autoMapped: true, assignedManually: false },
  { id: 'msg-20', sender: 'Elena', text: 'Can everyone confirm availability for tomorrow design-dev sync?', timestamp: 'Mar 2, 3:03 PM', nodeIds: ['meeting-sprint-planning'], autoMapped: true, assignedManually: false },
  { id: 'msg-21', sender: 'Derek', text: 'Render postgres rejected connection due to SSL mode mismatch.', timestamp: 'Mar 2, 3:22 PM', nodeIds: ['deploy-postgres'], autoMapped: true, assignedManually: false },
  { id: 'msg-22', sender: 'Jack', text: 'Logout flow still leaves stale state in one open tab.', timestamp: 'Mar 3, 9:05 AM', nodeIds: ['auth-logout'], autoMapped: true, assignedManually: false },
  { id: 'msg-23', sender: 'Priya', text: 'I reproduced that. Logout event is not broadcast to second tab.', timestamp: 'Mar 3, 9:09 AM', nodeIds: ['auth-logout'], autoMapped: true, assignedManually: false },
  { id: 'msg-24', sender: 'Alex', text: 'I added BroadcastChannel listener for logout and token clear.', timestamp: 'Mar 3, 9:16 AM', nodeIds: ['auth-logout'], autoMapped: true, assignedManually: false },
  { id: 'msg-25', sender: 'Nina', text: 'For response shape, should we keep both ownerName and owner object for one release?', timestamp: 'Mar 3, 9:33 AM', nodeIds: ['api-response-shape'], autoMapped: true, assignedManually: false },
  { id: 'msg-26', sender: 'Marco', text: 'Button disabled state contrast is low in dark mode, I will adjust.', timestamp: 'Mar 3, 9:46 AM', nodeIds: ['ui-button-states'], autoMapped: true, assignedManually: false },
  { id: 'msg-27', sender: 'Derek', text: 'Docker env fix deployed to staging, can someone verify login works there?', timestamp: 'Mar 3, 10:02 AM', nodeIds: ['deploy-docker-env'], autoMapped: true, assignedManually: false },
  { id: 'msg-28', sender: 'Elena', text: 'Tomorrow standup moved to 10:45 because of faculty meeting.', timestamp: 'Mar 3, 10:17 AM', nodeIds: ['meeting-sprint-planning'], autoMapped: true, assignedManually: false },
  { id: 'msg-29', sender: 'Sam', text: 'Great progress today everyone.', timestamp: 'Mar 3, 6:02 PM', nodeIds: ['topic-general'], autoMapped: true, assignedManually: false },
  { id: 'msg-30', sender: 'Jack', text: 'Verified: no more 401s after 30 minute token lifetime update.', timestamp: 'Mar 4, 9:22 AM', nodeIds: ['auth-401-expiration'], autoMapped: true, assignedManually: false },
  { id: 'msg-31', sender: 'Priya', text: 'Refresh token flow now triggers 2 minutes before expiration.', timestamp: 'Mar 4, 9:29 AM', nodeIds: ['auth-refresh'], autoMapped: true, assignedManually: false },
  { id: 'msg-32', sender: 'Nina', text: 'Request payload docs are published in Notion under API contract.', timestamp: 'Mar 4, 9:40 AM', nodeIds: ['api-validation'], autoMapped: true, assignedManually: false },
  { id: 'msg-33', sender: 'Marco', text: 'UI layout now matches Figma baseline grid in chat and map pages.', timestamp: 'Mar 4, 10:01 AM', nodeIds: ['ui-layout'], autoMapped: true, assignedManually: false },
  { id: 'msg-34', sender: 'Derek', text: 'Postgres connection stable now after forcing sslmode=require.', timestamp: 'Mar 4, 10:18 AM', nodeIds: ['deploy-postgres'], autoMapped: true, assignedManually: false },
  { id: 'msg-35', sender: 'Elena', text: 'Reminder: sprint demo run-through at 4:30 PM today.', timestamp: 'Mar 4, 10:21 AM', nodeIds: ['meeting-sprint-planning'], autoMapped: true, assignedManually: false },
  { id: 'msg-36', sender: 'Sam', text: 'I will post release notes draft in the general channel in an hour.', timestamp: 'Mar 4, 10:35 AM', nodeIds: ['topic-general'], autoMapped: true, assignedManually: false },
];

export const initialExpandedNodeIds = ['root-dev-team'];
