import { MapNodeData, Message } from './types';

// Wizard-of-Oz prototype seed data lives here.
export const initialNodes: MapNodeData[] = [
  {
    id: 'root-group-project',
    title: 'Group Project',
    parentId: null,
    summary: 'Shared topic map for the student group project planning chat.',
    metadata: {},
    decisions: [],
    supportingMessageIds: [],
    childrenIds: ['topic-planning', 'topic-assignments', 'topic-questions', 'topic-decisions', 'topic-issues', 'topic-general'],
    depth: 0,
  },
  {
    id: 'topic-planning',
    title: 'Planning',
    parentId: 'root-group-project',
    summary: 'Meeting logistics, schedule checkpoints, and project deliverable planning.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['planning-meeting-time', 'planning-timeline', 'planning-deliverables'],
    depth: 1,
  },
  {
    id: 'topic-assignments',
    title: 'Task Assignments',
    parentId: 'root-group-project',
    summary: 'Who owns each part of the project work and presentation.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['assign-research', 'assign-slides', 'assign-demo'],
    depth: 1,
  },
  {
    id: 'topic-questions',
    title: 'Questions & Concerns',
    parentId: 'root-group-project',
    summary: 'Open questions, uncertainty, and scope concerns from the team.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['question-scope', 'question-confusion'],
    depth: 1,
  },
  {
    id: 'topic-decisions',
    title: 'Decisions',
    parentId: 'root-group-project',
    summary: 'Agreed project choices so the team can move forward consistently.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['decision-topic', 'decision-tool'],
    depth: 1,
  },
  {
    id: 'topic-issues',
    title: 'Issues',
    parentId: 'root-group-project',
    summary: 'Blockers that could delay progress if not addressed quickly.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['issue-scheduling', 'issue-missing-work'],
    depth: 1,
  },
  {
    id: 'topic-general',
    title: 'General Chat',
    parentId: 'root-group-project',
    summary: 'General project conversation that does not fit a specific planning topic.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 1,
  },
  {
    id: 'planning-meeting-time',
    title: 'Meeting Time',
    parentId: 'topic-planning',
    summary: 'Discussion around next meeting dates and time windows.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'planning-timeline',
    title: 'Timeline',
    parentId: 'topic-planning',
    summary: 'Milestones and due-date checkpoints for finishing the project.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'planning-deliverables',
    title: 'Deliverables',
    parentId: 'topic-planning',
    summary: 'What final materials the group needs to submit and present.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: ['deliverable-presentation', 'deliverable-demo-script'],
    depth: 2,
  },
  {
    id: 'deliverable-presentation',
    title: 'Presentation Deck',
    parentId: 'planning-deliverables',
    summary: 'Slide deck content and completion progress for class presentation day.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: 'deliverable-demo-script',
    title: 'Demo Script',
    parentId: 'planning-deliverables',
    summary: 'Scripted walkthrough order so the live demo stays short and clear.',
    metadata: {},
    decisions: ['Keep the demo under 3 minutes', 'Assign one narrator and one operator'],
    supportingMessageIds: [],
    childrenIds: [],
    depth: 3,
  },
  {
    id: 'assign-research',
    title: 'Research',
    parentId: 'topic-assignments',
    summary: 'Who gathers examples, references, and project background context.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'assign-slides',
    title: 'Slides',
    parentId: 'topic-assignments',
    summary: 'Who builds and polishes the final slide deck.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'assign-demo',
    title: 'Demo',
    parentId: 'topic-assignments',
    summary: 'Who presents and runs the interactive walkthrough.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'question-scope',
    title: 'Scope Questions',
    parentId: 'topic-questions',
    summary: 'Questions about required project scope and expected depth.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'question-confusion',
    title: 'Confusion',
    parentId: 'topic-questions',
    summary: 'Clarifications needed when team members are unclear about deliverables.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'decision-topic',
    title: 'Final Topic',
    parentId: 'topic-decisions',
    summary: 'Final project concept selected by the group.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'decision-tool',
    title: 'Tool Choice',
    parentId: 'topic-decisions',
    summary: 'Chosen tools and stack for building the demo prototype.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'issue-scheduling',
    title: 'Scheduling Conflict',
    parentId: 'topic-issues',
    summary: 'Conflicts that make it hard to meet or rehearse together.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
  {
    id: 'issue-missing-work',
    title: 'Missing Work',
    parentId: 'topic-issues',
    summary: 'Needed project artifacts that are missing or still incomplete.',
    metadata: {},
    supportingMessageIds: [],
    childrenIds: [],
    depth: 2,
  },
];

export const initialMessages: Message[] = [
  { id: 'msg-1', sender: 'Jack Huber', text: 'Hey team, we should lock our project plan tonight so we can start building tomorrow.', timestamp: 'Apr 8, 7:02 PM', nodeIds: ['topic-planning'], autoMapped: true, assignedManually: false },
  { id: 'msg-2', sender: 'Boyd Coates', text: 'What time can everyone meet this week?', timestamp: 'Apr 8, 7:04 PM', nodeIds: ['planning-meeting-time'], autoMapped: true, assignedManually: false },
  { id: 'msg-3', sender: 'Emmanuel Jimenez', text: 'I can do Wednesday after 6, not earlier.', timestamp: 'Apr 8, 7:05 PM', nodeIds: ['planning-meeting-time'], autoMapped: true, assignedManually: false },
  { id: 'msg-4', sender: 'Graham Elgin', text: 'Thursday at 5 might be easier for me.', timestamp: 'Apr 8, 7:07 PM', nodeIds: ['planning-meeting-time'], autoMapped: true, assignedManually: false },
  { id: 'msg-5', sender: 'Jack Huber', text: 'Deadline check: outline due Friday, slides due Sunday.', timestamp: 'Apr 8, 7:11 PM', nodeIds: ['planning-timeline'], autoMapped: true, assignedManually: false },
  { id: 'msg-6', sender: 'Boyd Coates', text: 'Can we have a rough draft done by Saturday night?', timestamp: 'Apr 8, 7:13 PM', nodeIds: ['planning-timeline'], autoMapped: true, assignedManually: false },
  { id: 'msg-7', sender: 'Emmanuel Jimenez', text: 'What exactly are the deliverables besides the talk?', timestamp: 'Apr 8, 7:18 PM', nodeIds: ['planning-deliverables'], autoMapped: true, assignedManually: false },
  { id: 'msg-8', sender: 'Graham Elgin', text: 'We need a presentation deck and a short live demo.', timestamp: 'Apr 8, 7:20 PM', nodeIds: ['planning-deliverables'], autoMapped: true, assignedManually: false },
  { id: 'msg-9', sender: 'Jack Huber', text: 'I can own the research section and gather examples tonight.', timestamp: 'Apr 8, 7:25 PM', nodeIds: ['assign-research'], autoMapped: true, assignedManually: false },
  { id: 'msg-10', sender: 'Boyd Coates', text: 'I will build the slides once we have the final outline.', timestamp: 'Apr 8, 7:27 PM', nodeIds: ['assign-slides'], autoMapped: true, assignedManually: false },
  { id: 'msg-11', sender: 'Graham Elgin', text: 'I can run the demo in class if someone else narrates.', timestamp: 'Apr 8, 7:29 PM', nodeIds: ['assign-demo'], autoMapped: true, assignedManually: false },
  { id: 'msg-12', sender: 'Emmanuel Jimenez', text: 'Are we supposed to build a working app or just show a concept?', timestamp: 'Apr 8, 7:33 PM', nodeIds: ['question-scope'], autoMapped: true, assignedManually: false },
  { id: 'msg-13', sender: 'Boyd Coates', text: 'I am still confused about what counts as final deliverable quality.', timestamp: 'Apr 8, 7:36 PM', nodeIds: ['question-confusion'], autoMapped: true, assignedManually: false },
  { id: 'msg-14', sender: 'Jack Huber', text: 'Let us commit to chat mapping for student project planning.', timestamp: 'Apr 8, 7:42 PM', nodeIds: ['decision-topic'], autoMapped: true, assignedManually: false },
  { id: 'msg-15', sender: 'Graham Elgin', text: 'Decision: we should use React because we can move fastest with it.', timestamp: 'Apr 8, 7:45 PM', nodeIds: ['decision-tool'], autoMapped: true, assignedManually: false },
  { id: 'msg-16', sender: 'Emmanuel Jimenez', text: 'I cannot meet Wednesday night after all, lab got extended.', timestamp: 'Apr 8, 7:51 PM', nodeIds: ['issue-scheduling'], autoMapped: true, assignedManually: false },
  { id: 'msg-17', sender: 'Boyd Coates', text: 'I still have not seen the final outline doc in the folder.', timestamp: 'Apr 8, 7:54 PM', nodeIds: ['issue-missing-work'], autoMapped: true, assignedManually: false },
  { id: 'msg-18', sender: 'Jack Huber', text: 'For the presentation deck, keep it to six slides max.', timestamp: 'Apr 8, 8:01 PM', nodeIds: ['deliverable-presentation'], autoMapped: true, assignedManually: false },
  { id: 'msg-19', sender: 'Graham Elgin', text: 'I started a demo script with intro, map click-through, and wrap-up.', timestamp: 'Apr 8, 8:05 PM', nodeIds: ['deliverable-demo-script'], autoMapped: true, assignedManually: false },
  { id: 'msg-20', sender: 'Emmanuel Jimenez', text: 'Can someone drop the rubric link again?', timestamp: 'Apr 8, 8:12 PM', nodeIds: ['topic-general'], autoMapped: true, assignedManually: false },
  { id: 'msg-21', sender: 'Boyd Coates', text: 'Meeting update: Thursday 5:30 in the library room.', timestamp: 'Apr 9, 10:14 AM', nodeIds: ['planning-meeting-time'], autoMapped: true, assignedManually: false },
  { id: 'msg-22', sender: 'Jack Huber', text: 'Timeline check: research notes by Thursday night, slides by Sunday noon.', timestamp: 'Apr 9, 10:18 AM', nodeIds: ['planning-timeline'], autoMapped: true, assignedManually: false },
  { id: 'msg-23', sender: 'Graham Elgin', text: 'I can present the demo section and Boyd can handle transitions.', timestamp: 'Apr 9, 10:25 AM', nodeIds: ['assign-demo'], autoMapped: true, assignedManually: false },
  { id: 'msg-24', sender: 'Emmanuel Jimenez', text: 'I can help with research citations once Jack posts sources.', timestamp: 'Apr 9, 10:31 AM', nodeIds: ['assign-research'], autoMapped: true, assignedManually: false },
  { id: 'msg-25', sender: 'Boyd Coates', text: 'Slides are 40 percent done, waiting on final screenshots.', timestamp: 'Apr 9, 10:38 AM', nodeIds: ['assign-slides'], autoMapped: true, assignedManually: false },
  { id: 'msg-26', sender: 'Jack Huber', text: 'Decision confirmed: no backend for this demo, local data only.', timestamp: 'Apr 9, 10:44 AM', nodeIds: ['decision-tool'], autoMapped: true, assignedManually: false },
  { id: 'msg-27', sender: 'Graham Elgin', text: 'Are we sure we are not over-scoping this?', timestamp: 'Apr 9, 10:50 AM', nodeIds: ['question-scope'], autoMapped: true, assignedManually: false },
  { id: 'msg-28', sender: 'Emmanuel Jimenez', text: 'I am behind on my part because of two midterms this week.', timestamp: 'Apr 9, 10:56 AM', nodeIds: ['issue-missing-work'], autoMapped: true, assignedManually: false },
  { id: 'msg-29', sender: 'Boyd Coates', text: 'I might be 10 minutes late to Thursday meeting.', timestamp: 'Apr 9, 11:02 AM', nodeIds: ['issue-scheduling'], autoMapped: true, assignedManually: false },
  { id: 'msg-30', sender: 'Jack Huber', text: 'For deliverables, we submit slides plus one-page summary PDF.', timestamp: 'Apr 9, 11:08 AM', nodeIds: ['planning-deliverables'], autoMapped: true, assignedManually: false },
  { id: 'msg-31', sender: 'Graham Elgin', text: 'The demo script should include one manual reassignment example.', timestamp: 'Apr 9, 11:14 AM', nodeIds: ['deliverable-demo-script'], autoMapped: true, assignedManually: false },
  { id: 'msg-32', sender: 'Emmanuel Jimenez', text: 'I am not sure where this belongs but I can talk if needed.', timestamp: 'Apr 9, 11:22 AM', nodeIds: ['topic-general'], autoMapped: true, assignedManually: false },
  { id: 'msg-33', sender: 'Boyd Coates', text: 'Deck draft is up now, please review slide 3 and slide 4.', timestamp: 'Apr 9, 11:30 AM', nodeIds: ['deliverable-presentation'], autoMapped: true, assignedManually: false },
  { id: 'msg-34', sender: 'Jack Huber', text: 'Great, this gives us a clean story from messy chat to clear topics.', timestamp: 'Apr 9, 11:36 AM', nodeIds: ['topic-general'], autoMapped: true, assignedManually: false },
];

export const initialExpandedNodeIds = ['root-group-project'];
